"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# 파일 경로를 편리하게 처리하기 위함
from pathlib import Path

# 운영체제의 환경변수를 읽기 위함
import os

# .env 파일의 내용을 환경변수로 읽음
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 현재 프로젝트의 최상위 디렉터리를 구함 (프로젝트 루트임)
BASE_DIR = Path(__file__).resolve().parent.parent

# 프로젝트 루트의 .env 파일 읽음
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY 환경변수 적용
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv('DJANGO_DEBUG', 'True').lower() == 'true')  # 환경변수 적용

# 환경변수 적용
ALLOWED_HOSTS = [
    host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
]


# Application definition

INSTALLED_APPS = [
    # Django 관리자 사이트를 제공함
    'django.contrib.admin',

    # 사용자 인증과 권한 기능을 제공함
    'django.contrib.auth',

    # Model의 ContentType 을 관리함
    'django.contrib.contenttypes',

    # 사용자 로그인 세션을 관리함
    'django.contrib.sessions',

    # 성공/실패(오류) 안내 메시지를 관리함
    'django.contrib.messages',

    # CSS, Javascript 같은 정적 파일을 관리함
    'django.contrib.staticfiles',

    # 우리가 만든 앱 등록함 (장고가 앱을 인식하게 됨)
    # 회원 관리 앱 등록
    'members',

    # 게시판 앱 등록
    'boards',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        # Django Template 엔진을 사용함
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # 프로젝트 공통 templates 폴더를 지정함
        'DIRS': [BASE_DIR / 'templates']
        ,
        # 각 App 내부 Templates 폴더도 자동으로 검색함
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',

                # Template 에서 user 변수를 사용할 수 있게 함
                'django.contrib.auth.context_processors.auth',

                # Template 에서 messages를 사용할 수 있게 함
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        # .env 에서 값을 읽어옴
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        # 한글과 이모지 저장을 위해 utf8mb4 저장
        'options': {
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django 기본 auth.User 대신 members 앱의 Member를 사용자 Model로 지정함
AUTH_USER_MODEL = 'members.Member'
# @login_required 에서 로그인하지 않은 사용자를 이동시킬 url 이름 지정
LOGIN_URL = 'members:login'
# 로그아웃 후 이동할 기본 url 지정
LOGOUT_REDIRECT_URL = 'home'
# 사용자의 비활성 시간이 30분이 넘으면 세션을 만료시킴
SESSION_COOKIE_AGE = 30 * 60
# 요청이 발생할 때마다 세션 만료 시간을 다시 30분 연장되도록 설정
SESSION_SAVE_EVERY_REQUEST = True

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 사이트의 기본 언어를 한국어를 지정함
LANGUAGE_CODE = 'ko-kr'
# 서버와 템플릿에서 사용하는 표준 시간대를 서울로 지정함
TIME_ZONE = 'Asia/Seoul'
# Django 번역 기능을 활성화함
USE_I18N = True
# timezone-aware datetime 을 사용함
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 브라우저에서 정적 파일을 요청할 URL임
STATIC_URL = 'static/'

# 프로젝트의 static 폴더 위치 등록
STATICFILES_DIRS = [BASE_DIR / 'static']

# 사용자가 업로드한 파일을 요청할 URL임
MEDIA_URL = 'media/'

# 실제 업로드 파일이 저장되는 디렉터리임
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
